# Website details
name: "Vishnu Ks"
description: "Story of My Life"
email: "yo@vishnuks.com"
author: "Vishnu Ks"
lang: ""
locale: ""

# Jekyll
paginate: 10
highlighter: ""
markdown: kramdown
gems: [jekyll-paginate]
timezone: Asia/Kolkata
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: "vishnuks.com"
# Includes
disqusUsername: ""
googleAnalyticsId: "UA-105385860-1"

# Search engine verifications
bing: ""
yandex: ""
google: ""

#Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
    include_posts:
        - "/index.html"
    change_frequency_name: "daily"
    priority_name: "1.00"